/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import lombok.AccessLevel;
import lombok.Data;
import lombok.Setter;

import java.util.List;

public class Library {

    @Data()
    private static class Game {
        @Setter(AccessLevel.PRIVATE)
        private int homeScore;
        @Setter(AccessLevel.PRIVATE)
        private int awayScore;
        @Setter(AccessLevel.PRIVATE)
        private String homeName;
        @Setter(AccessLevel.PRIVATE)
        private String awayName;
        @Setter(AccessLevel.PRIVATE)
        private long creationTimestamp;
        @Setter(AccessLevel.PRIVATE)
        private int hash;
        private Game(String homeName, String awayName){
            this.homeName = homeName;
            this.awayName = awayName;
            creationTimestamp = System.currentTimeMillis();
            hash = (homeName + ' ' + awayName + creationTimestamp).hashCode();
        }
        @Override
        public int hashCode() {
            return hash;
        }
    }

    private static IDisplay display = new Display();

    public static void setDisplay(IDisplay display){
        Library.display = display;
    }

    public static Game startGame(String homeTeam, String awayTeam) {
        throw new UnsupportedOperationException();
    }

    public static void finishGame(Game identifier) {
        throw new UnsupportedOperationException();
    }

    public static void updateScore(Game identifier, int homeScore, int awayScore) {
        throw new UnsupportedOperationException();
    }

    public static List<Game> getASummaryOfGamesByTotalScore() {
        throw new UnsupportedOperationException();
    }
}
